sonar.projectKey=The1000y_ci_cd
sonar.organization=the1000y


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=ci_cd
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.test.inclusions=**/*_test.dart
sonar.tests=test
sonar.flutter.coverage.reportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.config.dart,**/generated/**
