sonar.projectKey=The1000y_ci_cd
sonar.organization=the1000y

sonar.projectName=ci_cd
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*_test.dart

sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8